
[[kernelarch]]
name = 'arm64'
  [[kernelarch.debianarch]]
  name = 'arm64'

[[kernelarch]]
name = 'x86'
  [[kernelarch.debianarch]]
  name = 'amd64'
  [[kernelarch.debianarch]]
  name = 'i386'
  [[kernelarch.debianarch]]
  name = 'x32'

[[featureset]]
name = 'none'

[[featureset]]
name = 'rt'
enable = true
  [featureset.description]
  parts = ['rt']
  [featureset.description.long]
  rt = 'This kernel includes the PREEMPT_RT realtime patch set.'
  [featureset.description.short]
  rt = 'PREEMPT_RT'

[build]
compiler = 'gcc'

[relations.image]
depends = [
  'dracut | linux-initramfs-tool',
]
recommends = [
  'apparmor',
]
breaks = [
  'fwupdate (<< 12-7)',
  'wireless-regdb (<< 2019.06.03-1~)',
]
