name: Backport kernel to existing releases
on:
  workflow_dispatch:
  push:
    branches:
      - 'maint-6.6'
jobs:
  backport:
    runs-on: ubuntu-latest
    # Matrix build for maintenance of multiple Garden Linux releases
    strategy:
      fail-fast: false
      matrix:
        branch: ['1443', '1592']
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: maint-6.6
      - run: |
            LATEST_COMMIT=$(git rev-parse --verify origin/maint-6.6)
            echo backporting commit $LATEST_COMMIT
            git config --global user.name "Garden Linux Builder"
            git config --global user.email "gardenlinux@users.noreply.github.com"
            git fetch origin
            git checkout origin/rel-${{ matrix.branch }}
            git checkout -b rel-${{ matrix.branch }}
            git cherry-pick $LATEST_COMMIT
            git push --set-upstream origin rel-${{ matrix.branch }}
